package com.org.framelt.notification.domain

enum class NotificationEventType {
    SIGN_UP,
    PROJECT_CREATION,
    PROJECT_APPLICATION,
    PROJECT_START,
    PROJECT_COMPLETE,
    PROJECT_SHOOTING_DAY,
    PROJECT_REVIEW_CREATED_FOR_HOST,
    PROJECT_REVIEW_CREATED_FOR_APPLICANT,
}
